### ISSUE TITLE
Would you provide your scraper?

### ISSUE THREAD

**Issue by Qriist** [vadimkotov/winapi-json#4]
Hello, thanks for this, I appreciate it! Would you mind making available the scraper and generation scripts you used to make these jsons?

I'd like to examine your scraping method and expand it to more fully cover the winApi. (I've noticed some headers are absent.)

Thanks in advance!

**Comment by marler8997** [comment]
I checked out this project a few years ago but I think it's been abondoned.  Luckily since then Microsoft has began publishing their API in this project: https://github.com/microsoft/win32metadata

They publish their API in a .NET binary format, but, I wrote a project that converts this .NET binary into JSON if you're interested: https://github.com/marlersoft/win32json

**Comment by Qriist** [comment]
Thanks for the heads up, I'll definitely take a look!

**Comment by vadimkotov** [comment]
Hey folks, unfortunately I have lost the scraper.
